"""Shared machine-facing contracts for CC Port agent integrations."""

from .contracts import (
    WIRE_CONTRACT_VERSION,
    WIRE_EXIT_INVALID_REQUEST,
    WIRE_EXIT_RUNTIME_FAILURE,
    WIRE_EXIT_SAFE_NONCOMPLETION,
    WIRE_EXIT_SUCCESS,
    AssetBatchChoiceWire,
    AssetBatchRequestWire,
    WireEnvelope,
    WireError,
    asset_action_approval_scope,
    asset_action_plan_hash,
    asset_batch_approval_scope,
    asset_batch_operation_id,
    parse_asset_batch_choices,
    parse_asset_batch_request,
    to_wire_value,
    wire_exit_code,
    wire_failure,
    wire_result,
    wire_success,
)

__all__ = [
    "WIRE_CONTRACT_VERSION",
    "WIRE_EXIT_INVALID_REQUEST",
    "WIRE_EXIT_RUNTIME_FAILURE",
    "WIRE_EXIT_SAFE_NONCOMPLETION",
    "WIRE_EXIT_SUCCESS",
    "AssetBatchChoiceWire",
    "AssetBatchRequestWire",
    "WireEnvelope",
    "WireError",
    "asset_action_approval_scope",
    "asset_action_plan_hash",
    "asset_batch_approval_scope",
    "asset_batch_operation_id",
    "parse_asset_batch_choices",
    "parse_asset_batch_request",
    "to_wire_value",
    "wire_exit_code",
    "wire_failure",
    "wire_result",
    "wire_success",
]
