[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$RepositoryName,
    [Parameter(Mandatory = $true)][string]$ReportPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Assert-EvidenceDirectory {
    param([string]$Path)
    $directory = [IO.DirectoryInfo]::new([IO.Path]::GetFullPath($Path).TrimEnd("\"))
    if ($directory.Name -notmatch '^e2e-[0-9]{8}T[0-9]{6}Z-[0-9a-f]{8}$' -or
        $null -eq $directory.Parent -or $directory.Parent.Name -ne "live-e2e" -or
        $null -eq $directory.Parent.Parent -or $directory.Parent.Parent.Name -ne "build") {
        throw "Report must stay in a generated build/live-e2e run directory."
    }
}

if ($RepositoryName -notmatch '^cc-port-e2e-[0-9]{8}-[0-9]{6}-[0-9a-f]{8}$') {
    throw "RepositoryName must be the unique name generated by preflight.py."
}
$ReportPath = [IO.Path]::GetFullPath($ReportPath)
if ([IO.Path]::GetFileName($ReportPath) -ne "github-repo.json") {
    throw "Repository report must be named github-repo.json."
}
if (Test-Path -LiteralPath $ReportPath) {
    throw "Refusing to overwrite an existing repository-creation report."
}
$reportParent = Split-Path -Parent $ReportPath
Assert-EvidenceDirectory -Path $reportParent
if (-not (Test-Path -LiteralPath $reportParent -PathType Container)) {
    throw "Report directory does not exist."
}
if (-not (Get-Command git.exe -ErrorAction SilentlyContinue)) {
    throw "Git for Windows is not available."
}

function Get-GitHubCredential {
    $request = "protocol=https`nhost=github.com`n`n"
    $lines = @($request | & git credential fill)
    if ($LASTEXITCODE -ne 0) {
        throw "Git Credential Manager did not return a GitHub credential."
    }
    $values = @{}
    foreach ($line in $lines) {
        $separator = $line.IndexOf("=")
        if ($separator -gt 0) {
            $values[$line.Substring(0, $separator)] = $line.Substring($separator + 1)
        }
    }
    if (-not $values.ContainsKey("password") -or [string]::IsNullOrWhiteSpace($values.password)) {
        throw "Git Credential Manager returned no GitHub secret."
    }
    return $values
}

function Invoke-GitHubApi {
    param(
        [Parameter(Mandatory = $true)][string]$Method,
        [Parameter(Mandatory = $true)][string]$Uri,
        [Parameter(Mandatory = $true)][hashtable]$Headers,
        [object]$Body
    )
    $arguments = @{
        Method = $Method
        Uri = $Uri
        Headers = $Headers
        ContentType = "application/json"
    }
    if ($null -ne $Body) {
        $arguments.Body = $Body | ConvertTo-Json -Depth 12 -Compress
    }
    return Invoke-RestMethod @arguments
}

$credential = Get-GitHubCredential
$headers = @{
    Accept = "application/vnd.github+json"
    Authorization = "Bearer $($credential.password)"
    "X-GitHub-Api-Version" = "2022-11-28"
    "User-Agent" = "cc-port-live-remote-e2e"
}

try {
    $user = Invoke-GitHubApi -Method Get -Uri "https://api.github.com/user" -Headers $headers
    if ([string]::IsNullOrWhiteSpace([string]$user.login)) {
        throw "GitHub did not return an authenticated login."
    }

    $repoBody = [ordered]@{
        name = $RepositoryName
        description = "Private repository for CC Port real remote Skill E2E validation."
        private = $true
        auto_init = $true
        has_issues = $false
        has_projects = $false
        has_wiki = $false
    }
    $repo = Invoke-GitHubApi -Method Post -Uri "https://api.github.com/user/repos" -Headers $headers -Body $repoBody
    if (-not $repo.private -or [string]$repo.name -ne $RepositoryName) {
        throw "GitHub returned an unexpected repository identity or visibility."
    }

    $registry = "version: 1`nresources: []`n"
    $registryBody = [ordered]@{
        message = "test: initialize Registry v1"
        content = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($registry))
        branch = [string]$repo.default_branch
    }
    $encodedName = [Uri]::EscapeDataString($RepositoryName)
    $registryResult = Invoke-GitHubApi -Method Put -Uri "https://api.github.com/repos/$($user.login)/$encodedName/contents/registry.yaml" -Headers $headers -Body $registryBody

    $report = [ordered]@{
        createdAtUtc = [DateTime]::UtcNow.ToString("o")
        owner = [string]$user.login
        repository = [string]$repo.name
        fullName = [string]$repo.full_name
        htmlUrl = [string]$repo.html_url
        cloneUrl = [string]$repo.clone_url
        private = [bool]$repo.private
        defaultBranch = [string]$repo.default_branch
        repositoryId = [long]$repo.id
        initialCommit = [string]$registryResult.commit.sha
        registrySha = [string]$registryResult.content.sha
        registryVersion = 1
        retainedByDefault = $true
    }
    [IO.File]::WriteAllText($ReportPath, ($report | ConvertTo-Json -Depth 8), [Text.UTF8Encoding]::new($false))
    Write-Output ($report | ConvertTo-Json -Compress)
} finally {
    if ($null -ne $credential) {
        $credential.password = ""
        $credential.Clear()
    }
    $headers.Authorization = ""
    $headers.Clear()
}
