[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$InstallerPath,
    [Parameter(Mandatory = $true)][string]$ExpectedInstallerSha256,
    [Parameter(Mandatory = $true)][string]$RepositoryName,
    [Parameter(Mandatory = $true)][string]$RepositoryUrl,
    [Parameter(Mandatory = $true)][string]$Branch,
    [Parameter(Mandatory = $true)][string]$EvidenceDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-CcPortUninstallEntries {
    $keys = @(
        "HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
    )
    return @(
        Get-ItemProperty $keys -ErrorAction SilentlyContinue |
            Where-Object {
                $property = $_.PSObject.Properties["DisplayName"]
                $null -ne $property -and [string]$property.Value -eq "CC Port"
            }
    )
}

function Assert-PathInside {
    param([string]$Path, [string]$Parent)
    $fullPath = [IO.Path]::GetFullPath($Path).TrimEnd("\")
    $fullParent = [IO.Path]::GetFullPath($Parent).TrimEnd("\")
    if (-not $fullPath.StartsWith($fullParent + "\", [StringComparison]::OrdinalIgnoreCase)) {
        throw "Test path escaped its required parent."
    }
}

function Convert-ToForwardPath {
    param([string]$Path)
    return $Path.Replace("\", "/")
}

function Assert-EvidenceDirectory {
    param([string]$Path)
    $directory = [IO.DirectoryInfo]::new([IO.Path]::GetFullPath($Path).TrimEnd("\"))
    if ($directory.Name -notmatch '^e2e-[0-9]{8}T[0-9]{6}Z-[0-9a-f]{8}$' -or
        $null -eq $directory.Parent -or $directory.Parent.Name -ne "live-e2e" -or
        $null -eq $directory.Parent.Parent -or $directory.Parent.Parent.Name -ne "build") {
        throw "EvidenceDirectory must be a generated build/live-e2e run directory."
    }
}

function Get-AvailableLoopbackPort {
    for ($attempt = 0; $attempt -lt 256; $attempt++) {
        $candidate = Get-Random -Minimum 49152 -Maximum 60001
        $listener = [Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback, $candidate)
        $listener.Server.ExclusiveAddressUse = $true
        try {
            $listener.Start()
            return $candidate
        } catch [Net.Sockets.SocketException] {
            continue
        } finally {
            $listener.Stop()
        }
    }
    throw "Could not reserve a usable loopback port for WebView2 debugging."
}

if ($RepositoryName -notmatch '^cc-port-e2e-[0-9]{8}-[0-9]{6}-[0-9a-f]{8}$') {
    throw "RepositoryName must be generated by preflight.py."
}
if ($RepositoryUrl -notmatch ('^https://github\.com/[^/]+/' + [regex]::Escape($RepositoryName) + '\.git$')) {
    throw "RepositoryUrl does not match RepositoryName."
}
if ($Branch -ne "main") {
    throw "Live E2E currently requires the main branch."
}
if ($ExpectedInstallerSha256 -notmatch '^[0-9a-fA-F]{64}$') {
    throw "ExpectedInstallerSha256 is malformed."
}
$installer = [IO.Path]::GetFullPath($InstallerPath)
if (-not (Test-Path -LiteralPath $installer -PathType Leaf)) {
    throw "Installer does not exist."
}
$actualInstallerSha256 = (Get-FileHash -LiteralPath $installer -Algorithm SHA256).Hash
if (-not $actualInstallerSha256.Equals($ExpectedInstallerSha256, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Installer hash changed after preflight."
}
$evidence = [IO.Path]::GetFullPath($EvidenceDirectory).TrimEnd("\")
Assert-EvidenceDirectory -Path $evidence
if (-not (Test-Path -LiteralPath $evidence -PathType Container)) {
    throw "EvidenceDirectory does not exist."
}
$contextPath = Join-Path $evidence "session-context.json"
$stopSignalPath = Join-Path $evidence "session-stop.signal"
$cleanupReportPath = Join-Path $evidence "session-cleanup.json"
foreach ($path in @($contextPath, $stopSignalPath, $cleanupReportPath)) {
    Assert-PathInside -Path $path -Parent $evidence
}
if ((Test-Path -LiteralPath $contextPath) -or (Test-Path -LiteralPath $cleanupReportPath)) {
    throw "Refusing to overwrite an existing session context or cleanup report."
}
Remove-Item -LiteralPath $stopSignalPath -Force -ErrorAction SilentlyContinue

$git = Get-Command git.exe -ErrorAction SilentlyContinue
if ($null -eq $git) {
    throw "Git for Windows is not available."
}
$gitExecutable = [IO.Path]::GetFullPath($git.Source)
$testId = [guid]::NewGuid().ToString("N")
$tempParent = [IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd("\")
$testRoot = Join-Path $tempParent ("cc-port-live-e2e-" + $testId)
$installDir = Join-Path $testRoot "app"
$stateDir = Join-Path $testRoot "state"
$configDir = Join-Path $testRoot "config"
$configPath = Join-Path $configDir "config.toml"
$webViewDir = Join-Path $testRoot "webview"
$toolHome = Join-Path $testRoot "tool-home"
$skillRoot = Join-Path $toolHome "skills"
$fixtureDir = Join-Path $skillRoot "cc-port-e2e-skill"
$fixtureReferenceDir = Join-Path $fixtureDir "references"
$mcpPath = Join-Path $toolHome "mcp.json"
$resourceRepo = Join-Path $testRoot "resource-checkout"
$fixtureBackup = Join-Path $testRoot "fixture-backup"
$debugPort = Get-AvailableLoopbackPort
$desktop = $null
$uninstaller = $null
$cleanupErrors = New-Object System.Collections.Generic.List[string]
$ready = $false

Assert-PathInside -Path $testRoot -Parent $tempParent
New-Item -ItemType Directory -Path $testRoot, $configDir, $toolHome, $fixtureReferenceDir -Force | Out-Null

try {
    if (@(Get-CcPortUninstallEntries).Count -ne 0) {
        throw "CC Port is already installed; refusing to replace a user installation."
    }
    $installerProcess = Start-Process -FilePath $installer -ArgumentList @("/S", "/D=$installDir") -Wait -PassThru
    if ($installerProcess.ExitCode -ne 0) {
        throw "Installer failed with exit code $($installerProcess.ExitCode)."
    }
    $desktopExe = Join-Path $installDir "cc-port-desktop.exe"
    $sidecarExe = Join-Path $installDir "cc-port-desktop-api.exe"
    $agentExe = Join-Path $installDir "cc-port.exe"
    $uninstaller = Get-ChildItem -LiteralPath $installDir -File -Filter "*uninstall*.exe" | Select-Object -First 1
    if (-not (Test-Path -LiteralPath $desktopExe -PathType Leaf) -or
        -not (Test-Path -LiteralPath $sidecarExe -PathType Leaf) -or
        -not (Test-Path -LiteralPath $agentExe -PathType Leaf) -or
        $null -eq $uninstaller) {
        throw "Installed desktop, sidecar, agent, or uninstaller is missing."
    }

    $skillText = @'
---
name: cc-port-e2e-skill
description: Harmless fixture used to prove CC Port real remote upload and installation.
---

# CC Port real remote E2E Skill

This fixture contains no credentials and performs no actions. Its exact bytes are verified after download.

The references/proof.md file is inert test content.
'@ -replace "`r`n", "`n"
    $referenceText = @'
# Proof payload

fixture-id: cc-port-real-remote-e2e-v1
expected-direction: local-to-remote-then-remote-to-local
'@ -replace "`r`n", "`n"
    [IO.File]::WriteAllText((Join-Path $fixtureDir "SKILL.md"), $skillText, [Text.UTF8Encoding]::new($false))
    [IO.File]::WriteAllText((Join-Path $fixtureReferenceDir "proof.md"), $referenceText, [Text.UTF8Encoding]::new($false))

    $configText = @"
[git]
executable = "$(Convert-ToForwardPath $gitExecutable)"

[resources]
repo_name = "$RepositoryName"
repo_url = "$RepositoryUrl"
local_path = "$(Convert-ToForwardPath $resourceRepo)"
branch = "$Branch"
credential_mode = "native"

[platforms.package-test]
tool_id = "cursor"
environment_kind = "windows"
environment_name = ""
display_name = "CC Port Live Remote E2E"
home_dir = "$(Convert-ToForwardPath $toolHome)"
enabled = true
skills_dir = "$(Convert-ToForwardPath $skillRoot)"
mcp_json = "$(Convert-ToForwardPath $mcpPath)"
rules_dir = ""
prompts_dir = ""
plugins_dir = ""
instructions_path = ""
memories_dir = ""
settings_path = ""
"@
    [IO.File]::WriteAllText($configPath, $configText, [Text.UTF8Encoding]::new($false))

    $env:CC_PORT_CONFIG = $configPath
    $env:CC_PORT_STATE_HOME = $stateDir
    $env:WEBVIEW2_USER_DATA_FOLDER = $webViewDir
    $env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$debugPort"
    $desktop = Start-Process -FilePath $desktopExe -PassThru

    $deadline = [DateTime]::UtcNow.AddSeconds(45)
    do {
        $desktop.Refresh()
        if (-not $desktop.HasExited -and $desktop.MainWindowHandle -ne [IntPtr]::Zero) {
            break
        }
        Start-Sleep -Milliseconds 250
    } while ([DateTime]::UtcNow -lt $deadline)
    if ($desktop.HasExited -or $desktop.MainWindowHandle -eq [IntPtr]::Zero) {
        throw "Installed desktop window did not become ready."
    }

    $context = [ordered]@{
        schemaVersion = 1
        testId = $testId
        testRoot = $testRoot
        evidenceDirectory = $evidence
        installDir = $installDir
        stateDir = $stateDir
        configPath = $configPath
        webViewDir = $webViewDir
        toolHome = $toolHome
        skillRoot = $skillRoot
        fixtureDir = $fixtureDir
        fixtureBackup = $fixtureBackup
        mcpPath = $mcpPath
        resourceRepo = $resourceRepo
        repositoryName = $RepositoryName
        repositoryUrl = $RepositoryUrl
        branch = $Branch
        desktopExe = $desktopExe
        sidecarExe = $sidecarExe
        agentExe = $agentExe
        installerSha256 = $actualInstallerSha256
        fixtureSkillSha256 = (Get-FileHash -LiteralPath (Join-Path $fixtureDir "SKILL.md") -Algorithm SHA256).Hash
        fixtureProofSha256 = (Get-FileHash -LiteralPath (Join-Path $fixtureReferenceDir "proof.md") -Algorithm SHA256).Hash
        pid = $desktop.Id
        mainWindowHandle = $desktop.MainWindowHandle.ToInt64()
        debugPort = $debugPort
        startedAtUtc = [DateTime]::UtcNow.ToString("o")
    }
    [IO.File]::WriteAllText($contextPath, ($context | ConvertTo-Json -Depth 6), [Text.UTF8Encoding]::new($false))
    $ready = $true
    Write-Output ("READY " + ($context | ConvertTo-Json -Compress))

    $sessionDeadline = [DateTime]::UtcNow.AddMinutes(25)
    do {
        $desktop.Refresh()
        if ($desktop.HasExited -or (Test-Path -LiteralPath $stopSignalPath -PathType Leaf)) {
            break
        }
        Start-Sleep -Milliseconds 500
    } while ([DateTime]::UtcNow -lt $sessionDeadline)
} finally {
    try {
        if ($null -ne $desktop) {
            $desktop.Refresh()
            if (-not $desktop.HasExited) {
                Stop-Process -Id $desktop.Id -Force -ErrorAction SilentlyContinue
                $desktop.WaitForExit(10000) | Out-Null
            }
        }
    } catch {
        $cleanupErrors.Add("desktop: $($_.Exception.Message)")
    }
    try {
        if ($null -ne $uninstaller -and (Test-Path -LiteralPath $uninstaller.FullName -PathType Leaf)) {
            $uninstall = Start-Process -FilePath $uninstaller.FullName -ArgumentList "/S" -Wait -PassThru
            if ($uninstall.ExitCode -ne 0) {
                $cleanupErrors.Add("uninstaller-exit-$($uninstall.ExitCode)")
            }
        }
    } catch {
        $cleanupErrors.Add("uninstaller: $($_.Exception.Message)")
    }
    try {
        Start-Sleep -Milliseconds 750
        Assert-PathInside -Path $testRoot -Parent $tempParent
        if (Test-Path -LiteralPath $testRoot) {
            Remove-Item -LiteralPath $testRoot -Recurse -Force
        }
    } catch {
        $cleanupErrors.Add("temporary-root: $($_.Exception.Message)")
    }
    Remove-Item -LiteralPath $stopSignalPath -Force -ErrorAction SilentlyContinue
    $cleanup = [ordered]@{
        ready = $ready
        testId = $testId
        finishedAtUtc = [DateTime]::UtcNow.ToString("o")
        uninstallEntriesRemaining = @(Get-CcPortUninstallEntries).Count
        testRootRemoved = -not (Test-Path -LiteralPath $testRoot)
        cleanupErrors = $cleanupErrors.ToArray()
    }
    [IO.File]::WriteAllText($cleanupReportPath, ($cleanup | ConvertTo-Json -Depth 5), [Text.UTF8Encoding]::new($false))
    Write-Output ("CLEANUP " + ($cleanup | ConvertTo-Json -Compress))
}
